schema_version = "1.0.0"
id = "commotion"
version = "2.4.2"
name = "Commotion"
tagline = "Animation offset tools for motion graphics"
maintainer = "Mikhail Rachinskiy"
type = "add-on"
tags = ["Animation"]
blender_version_min = "4.2.0"
website = "https://github.com/mrachinskiy/commotion"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2014-2024 Mikhail Rachinskiy"]
